version: 2.1
commands:
  print-pipeline-id:
    description: "Prints out the pipeline ID"
    parameters:
      to:
        type: string
        default: "None"
      steps:
        - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  run-pipeline-id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - print-pipeline-id
          
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello!"

  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say World"
          command: "echo world!"

  print-my-name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo $MY_NAME
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-my-name
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - run-pipeline-id